### ISSUE TITLE
Unsafe usage of PyYAML yaml.load()

### ISSUE THREAD

**Issue by gkmr507** [itiskrishnas/yamldown#1]
The default behavior of PyYAML's yaml.load() method is unsafe and can execute code in yaml files.
yaml.safe_load() should be used instead: https://github.com/yaml/pyyaml/issues/193#issuecomment-457387449

https://github.com/dougli1sqrd/yamldown/blob/480957d59da215e75be9c0b4312406a18185bb9b/yamldown/yamldown.py#L34

**Comment by itiskrishnas** [comment]
#

**Comment by itiskrishnas** [comment]
[fix](https://github.com/itiskrishnas/yamldown/commit/73a15b2e5a6feaae93ba38a7bc1f58c8d530654d)
